# Site settings

title: "Presentations by Szymon Kulec @Scooletz"
description: "Presentations by Szymon Kulec @Scooletz"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://presentations.scooletz.com" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

highlighter: rouge
markdown: kramdown
exclude: 
- README.md
- .gitignore
- CNAME

encoding: utf-8

output: true