name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read
  deployments: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Cache bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock', '**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: pages deploy _site --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --commit-dirty=true
